#!/bin/bash

# 获取当前目录并存储在变量中
current_directory=$(cd "$(dirname "$0")" && pwd)
# 程序依赖文件夹
app_files="$current_directory/Contents"
# 图片压缩器
tinypng="$app_files/tinypng"
# webp转换器
cwebp="$app_files/cwebp"
# 图片文件夹
img_files="$current_directory/img"
# 输出文件夹
output_files="$current_directory/output"
# webp 文件夹
webp="$output_files/webp"

main_img_size=220
cover_img_size=160

# 清除终端显示
clear

# 欢迎使用
echo "欢迎使用图片压缩工具, 免费压缩次数为500次/月。"
echo "待压缩的图片请放入 img"

# 创建输出和webp文件夹
mkdir -p "$output_files" "$webp"

# 输出当前目录下的img文件夹中不同格式的图片文件的数量
echo "待压缩图片文件数量："
echo "------------------------"
for ext in jpg jpeg png gif; do
  count=$(find "$img_files" -maxdepth 1 -type f -iname "*.$ext" | wc -l)
  echo "$ext:   $count 张"
done

echo "------------------------"

# 询问处理的图片类型
echo "请选择压缩类型："
echo "1.内容图"
echo "2.封面图"
read -n1 -p "请输入您的选择 (1-2): " compress_type
echo

compress_image() {
    local label=$1
    local width=$2
    local height=$3
    echo "开始压缩 $label 图"
    "$tinypng" "$img_files" --width "$width" --height "$height"
    find "$img_files" -type f \( -name "裁剪-*.jpg" -o -name "裁剑-*.png" \) -exec sh -c 'file={}; mv "$file" "$2/'"$label"'$(basename "$file")"' _ {} "$output_files" \;
}

case $compress_type in
  1)  
    compress_image "内容" 750 1000
    type=1
    ;;
  2)
    compress_image "封面" 690 518
    type=2
    ;;
  *)
    echo "无效输入，请输入 1-2 之间的数字。"
    exit 1
    ;;
esac


# 提示开始转换webp格式
convert_to_webp() {
  echo "是否继续转换为webp (Y/N): "
  read -n1 webpyes
  echo
  case $webpyes in
    Y|y)  
      echo "开始转换"
      export DYLD_FALLBACK_LIBRARY_PATH="$app_files/libs"
      find "$output_files" -type f \( -iname "*裁剪-*.jpg" -o -iname "*裁剪-*.jpeg" -o -iname "*裁剪-*.png" -o -iname "*裁剪-*.gif" \) | while read -r file; do
          "$cwebp" -lossless -m 6 "$file" -o "$webp/$(basename "$file" .jpg).webp"
      done
      echo "压缩完成"
      echo "------------------------"
      echo "按任意键打开压缩后的图片文件夹"
      read -r
      open "$img_files"
      ;;
    N|n)
      echo "感谢使用"
      exit 0
      ;;
    *)
      ;;
  esac
}

process_images() {
    local img_size=$1
    find "$output_files" -type f \( -name "*裁剪-*.jpg" -o -name "*裁剪-*.png" \) | while read file; do
        file_size=$(du -k "$file" | cut -f1)
        if [ "$file_size" -gt "$img_size" ]; then
            echo "$file 超出限制，可以尝试转换成webp。"
            convert_to_webp
        else
            echo "$file 合格"
            echo "没有需要转换的图片"
            exit 0
        fi
    done
}

# 根据压缩的类型做不同的判断
if [ "$type" -eq 1 ]; then
    process_images "$main_img_size"
elif [ "$type" -eq 2 ]; then
    process_images "$cover_img_size"
else
    echo "没有需要转换的图片"
    exit 0
fi
